<?php if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_company-information',
		'title' => 'Company Information',
		'fields' => array (
			array (
				'key' => 'field_53d0ec39195fa',
				'label' => 'Company Logo',
				'name' => '',
				'type' => 'tab',
				'instructions' => 'Upload the company logo here',
				'required' => 1,
			),
			array (
				'key' => 'field_53d0ed232a46d',
				'label' => 'Company Logo',
				'name' => 'company_logo',
				'type' => 'image',
				'instructions' => 'Upload the company logo here',
				'required' => 1,
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_53d0ec59195fb',
				'label' => 'Phone & Email',
				'name' => '',
				'type' => 'tab',
				'instructions' => 'Please enter the company phone numbers.',
				'required' => 1,
			),
			array (
				'key' => 'field_53d0f2aa52db2',
				'label' => 'Phone Strap Line',
				'name' => 'phone_strap_line',
				'type' => 'text',
				'instructions' => 'e.g. Call Us Today!',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 30,
			),
			array (
				'key' => 'field_53d0ed472a46e',
				'label' => 'Company Phone',
				'name' => 'company_phone',
				'type' => 'repeater',
				'instructions' => 'Please enter the company phone numbers.',
				'required' => 1,
				'sub_fields' => array (
					array (
						'key' => 'field_53d0f30a52db3',
						'label' => 'Phone Label',
						'name' => 'phone_label',
						'type' => 'text',
						'instructions' => 'This is the label for the Google Analytics call tracking. e.g. Landline',
						'column_width' => 40,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53d0ed472a46f',
						'label' => 'Phone Number',
						'name' => 'phone_number',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => 3,
				'layout' => 'table',
				'button_label' => 'Add Number',
			),
			array (
				'key' => 'field_543d00e15f6d6',
				'label' => 'Opening Times',
				'name' => 'opening_times',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_543d00f25f6d7',
						'label' => 'Day',
						'name' => 'day',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_543d011c5f6d8',
						'label' => 'Open',
						'name' => 'open',
						'type' => 'text',
						'instructions' => '24 hours',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_543d018883dc4',
						'label' => 'Close',
						'name' => 'close',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_53dbacc590640',
				'label' => 'Main Email Address',
				'name' => 'email_address',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53d0ecc12a46c',
				'label' => 'Company Address',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53d0ed622a470',
				'label' => 'Building Number/Name',
				'name' => 'building_number',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53d0f10b7b22e',
				'label' => 'Add Line Break?',
				'name' => 'add_line_break',
				'type' => 'radio',
				'instructions' => 'Do you want the street name to be on a new line?',
				'choices' => array (
					'Yes' => 'Yes',
					'No' => 'No',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'No',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53d0ed962a471',
				'label' => 'Street Name',
				'name' => 'street_name',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53d0edfd2a472',
				'label' => 'Town / City',
				'name' => 'town_city',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53d0ee162a473',
				'label' => 'County',
				'name' => 'county',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53d0ee1e2a474',
				'label' => 'Post Code',
				'name' => 'post_code',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53d0ee712a475',
				'label' => 'Company Numbers',
				'name' => '',
				'type' => 'tab',
				'instructions' => 'If they have a registered company number, please enter this here.',
			),
			array (
				'key' => 'field_53d0ef6c3811a',
				'label' => 'Company Number',
				'name' => 'company_number',
				'type' => 'text',
				'instructions' => 'If they have a registered company number, please enter this here.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53d0ef833811b',
				'label' => 'VAT Number',
				'name' => 'vat_number',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53d6737fb2ea8',
				'label' => 'Google Map & Areas Covered',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53e0a5ce716f0',
				'label' => 'Google Maps',
				'name' => 'google_maps',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_53e0a718e54ed',
						'label' => 'Location Co-ords',
						'name' => 'location_coords',
						'type' => 'repeater',
						'instructions' => 'The company location',
						'column_width' => 50,
						'sub_fields' => array (
							array (
								'key' => 'field_53e0a79ee54ef',
								'label' => 'Lattitude',
								'name' => 'loc_lattitude',
								'type' => 'text',
								'column_width' => 50,
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53e0a764e54ee',
								'label' => 'Longitude',
								'name' => 'loc_longitude',
								'type' => 'text',
								'column_width' => 50,
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_53e0a7b7e54f0',
						'label' => 'Map Centre Co-ords',
						'name' => 'centre_coords',
						'type' => 'repeater',
						'instructions' => 'The centre of the map',
						'column_width' => 50,
						'sub_fields' => array (
							array (
								'key' => 'field_53e0a7b7e54f2',
								'label' => 'Lattitude',
								'name' => 'cen_lattitude',
								'type' => 'text',
								'column_width' => 50,
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53e0a7b7e54f1',
								'label' => 'Longitude',
								'name' => 'cen_longitude',
								'type' => 'text',
								'column_width' => 50,
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
				),
				'row_min' => 1,
				'row_limit' => 1,
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_53d6754c31d0e',
				'label' => 'Areas We Cover',
				'name' => 'areas_we_cover',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_53d6757531d0f',
						'label' => 'Town / City',
						'name' => 'town_/_city',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Town / City',
			),
			array (
				'key' => 'field_54de0ea721197',
				'label' => 'Services',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54de0eaf21198',
				'label' => 'Our Services',
				'name' => 'our_services',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_54de0ebc21199',
						'label' => 'Icon',
						'name' => 'icon',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_54de0fde2119a',
						'label' => 'Service',
						'name' => 'service',
						'type' => 'text',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 2,
				'row_limit' => 8,
				'layout' => 'table',
				'button_label' => 'Add Service',
			),
			array (
				'key' => 'field_54e36736399d7',
				'label' => 'Accreditations',
				'name' => 'accreditations',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_54e368ee399d8',
						'label' => 'Accreditation',
						'name' => 'accreditation',
						'type' => 'image',
						'required' => 1,
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
				),
				'row_min' => 1,
				'row_limit' => 2,
				'layout' => 'table',
				'button_label' => 'Add Accreditation',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
?>